using System;
using System.Collections.Generic;
using System.Text;

namespace EasyMapper.Common
{
    internal class Constants
    {
        internal const string SystemNamespace = "System";
        internal const string RootNamespace = "OBS.BSP.Analyzer.SourceGenerator";
        internal const string GeneratedFileHeader = "// <auto-generated />";
    }
}
